package:
  name: perspective-python
  version: 2.0.1
  top-level:
    - perspective
source:
  # url: https://files.pythonhosted.org/packages/08/c1/ea69d50036ca9f81d158508c507a05a05a6cb9e1ab82532ea627f7e11339/perspective-python-2.0.1.tar.gz
  # sha256: 7f8470963c506ccf89768983997a92d9c7797c199c11b41ce294ee77101004ce
  path: ../../perspective-src/python/perspective
build:
  cxxflags: -fexceptions
  ldflags: -fexceptions
  # TODO: this duplicates what yarn build_python --setup does
  # maybe just run yarn (or yarn install a subset of packages), then
  # yarn build_python --setup; then overwrite the dist dir?
  cross-script: |
    echo $PYODIDE_ROOT
    PATCH_ROOT=$PYODIDE_ROOT/perspective-src
    pwd
    rm -rf dist/
    mkdir dist
    cp -rp $PATCH_ROOT/{LICENSE,README.md} dist/
    cp -rp $PATCH_ROOT/cmake dist/
    cp -rp $PATCH_ROOT/cpp/perspective/{CMakeLists.txt,src} dist/
    cp -rp $PATCH_ROOT/python/perspective python/
requirements:
  host:
    - numpy
    - boost-cpp
  run:
    - distutils
    - ipywidgets
    # - future
    - numpy
    - pandas
    - python-dateutil
    - pytz
    - traitlets
about:
  home: https://github.com/finos/perspective
  PyPI: https://pypi.org/project/perspective-python
  summary: Python bindings and JupyterLab integration for Perspective
  license: Apache 2.0
