package:
  name: perspective-python
  version: 2.0.1
  top-level:
    - perspective
source:
  # url: https://files.pythonhosted.org/packages/e5/eb/f835602e295333e86b3f38d91dfe2a7f08040870d0aae9750ac2cc6874fa/perspective-python-2.0.1.tar.gz
  # sha256: 7f8470963c506ccf89768983997a92d9c7797c199c11b41ce294ee77101004ce
  # path: /Users/tom/perspective/_/jupyterlite-nasty/python/perspective
  path: perspective-src/python/perspective
build:
  cxxflags: -fexceptions
  ldflags: -fexceptions
requirements:
  host:
    - numpy
  run:
    - distutils
    # - future
    - numpy
    - pandas
    - python-dateutil
    - pytz
about:
  home: https://github.com/finos/perspective
  PyPI: https://pypi.org/project/perspective-python
  summary: Python bindings and JupyterLab integration for Perspective
  license: Apache 2.0
